"""Collections voice agent -- entry point.

Text call:   .venv\\Scripts\\python.exe src\\main.py
Voice call:  .venv\\Scripts\\python.exe src\\main.py --voice

Type/say 'bye' to hang up.
"""

import os
import sys
import time

import requests
from dotenv import load_dotenv

import calllog
import rag
from brain import MODEL, ask_brain, build_system_prompt
from records import format_record, load_customers

RETRY_LINE = "I'm sorry, I'm having a brief technical issue. Could you say that once more?"

OPENING = (
    "Hi, this is Maya, an automated assistant calling from Horizon Bank "
    "regarding your account. Am I speaking with {name}?"
)

HANGUP_WORDS = {"quit", "exit", "bye", "goodbye"}


def pick_customer(customers):
    print("Which customer is Maya dialling today?\n")
    for i, customer in enumerate(customers, start=1):
        print(f"  {i}. {customer['name']} (balance: {customer['balance']} rupees)")
    valid = {str(n) for n in range(1, len(customers) + 1)}
    while True:
        choice = input(f"\nPick 1-{len(customers)}: ").strip()
        if choice in valid:
            return customers[int(choice) - 1]
        print("Just the digit, e.g. 1")


def main():
    voice_mode = "--voice" in sys.argv

    load_dotenv()
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key or api_key.startswith("paste"):
        print("No API key found. Copy .env.example to .env and paste your")
        print("Gemini key (aistudio.google.com/apikey) after GEMINI_API_KEY=")
        return

    print("Indexing bank policies...")
    policy_index = rag.build_index(api_key)

    cfg = asr_model = voice = None
    if voice_mode:
        import voice

        cfg = voice.load_config()
        print("Loading the speech recognition model...")
        asr_model = voice.load_asr_model(cfg)

    customers = load_customers()
    customer = pick_customer(customers)
    record_text = format_record(customer)
    log_path = calllog.start_call(customer["name"], "voice" if voice_mode else "text")

    print("\n--- ringing... call connected ---\n")

    # The opening line is scripted in code, not generated by the LLM:
    # compliance-critical wording should be deterministic, every call.
    opening = OPENING.format(name=customer["name"])
    print(f"Maya: {opening}\n")
    if voice_mode:
        voice.speak(opening, cfg)
    history = [{"role": "model", "text": opening}]

    while True:
        timings = {}

        if voice_mode:
            print("(listening...)")
            t0 = time.perf_counter()
            user_text = voice.listen(cfg, asr_model)
            timings["asr_ms"] = round((time.perf_counter() - t0) * 1000)
            if not user_text:
                print("(heard nothing)")
                voice.speak("Sorry, I didn't catch that. Could you say that again?", cfg)
                continue
            print(f"You: {user_text}")
        else:
            user_text = input("You: ").strip()
            if not user_text:
                continue

        spoken_words = {w.strip(".,!?;:") for w in user_text.lower().split()}
        if spoken_words & HANGUP_WORDS:
            closing = "Thank you for your time. Goodbye!"
            print(f"\nMaya: {closing}")
            if voice_mode:
                voice.speak(closing, cfg)
            print("\n--- call ended ---")
            break

        history.append({"role": "user", "text": user_text})

        # Retrieve on a context window, not just the latest words. A one-word
        # reply like "yes" carries no meaning on its own, so a short follow-up
        # borrows Maya's previous line to find the policy the caller means.
        retrieval_query = user_text
        if len(user_text.split()) <= 3 and len(history) >= 2:
            retrieval_query = history[-2]["text"] + " " + user_text

        # A retrieval failure degrades to "no policy context", never a crash.
        t0 = time.perf_counter()
        try:
            policy_chunks = rag.retrieve(api_key, policy_index, retrieval_query)
        except requests.RequestException:
            policy_chunks = []
        timings["retrieval_ms"] = round((time.perf_counter() - t0) * 1000)
        policy_text = rag.format_policy_context(policy_chunks)
        system_prompt = build_system_prompt(customer, record_text, policy_text)

        # A phone bot must never go silent: if the LLM call fails (rate
        # limit, network), Maya asks the caller to repeat instead of crashing.
        # The real reason is printed to the console for whoever runs the bot.
        t0 = time.perf_counter()
        try:
            reply = ask_brain(api_key, system_prompt, history)
        except requests.RequestException as e:
            status = getattr(e.response, "status_code", None)
            if status == 429:
                print(f"  [{MODEL} free-tier daily quota exhausted — try again tomorrow, "
                      f"or switch MODEL in brain.py to a model with quota left]")
            else:
                print(f"  [model call failed after 1 retry: {e}]")
            reply = RETRY_LINE
        timings["llm_ms"] = round((time.perf_counter() - t0) * 1000)
        history.append({"role": "model", "text": reply})
        print(f"\nMaya: {reply}\n")

        if voice_mode:
            t0 = time.perf_counter()
            voice.speak(reply, cfg)
            timings["tts_ms"] = round((time.perf_counter() - t0) * 1000)

        calllog.log_turn(
            log_path,
            user_text,
            reply,
            [f"{c['doc']} / {c['heading']}" for c in policy_chunks],
            timings,
        )


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n--- call ended (interrupted) ---")
