"""Collections voice agent -- stage 1: the brain on rails (text chat).

Run from the project root:
    .venv\\Scripts\\python.exe src\\main.py

You play the customer typing replies; Maya answers via the LLM.
Type 'quit' to hang up.
"""

import os

from dotenv import load_dotenv

from brain import ask_brain, build_system_prompt
from records import format_record, load_customers

OPENING = (
    "Hi, this is Maya, an automated assistant calling from Horizon Bank "
    "regarding your account. Am I speaking with {name}?"
)


def pick_customer(customers):
    print("Which customer is Maya dialling today?\n")
    for i, customer in enumerate(customers, start=1):
        print(f"  {i}. {customer['name']} (balance: {customer['balance']} rupees)")
    while True:
        choice = input("\nPick 1-3: ").strip()
        if choice in {"1", "2", "3"}:
            return customers[int(choice) - 1]
        print("Just the digit, e.g. 1")


def main():
    load_dotenv()
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key or api_key.startswith("paste"):
        print("No API key found. Copy .env.example to .env and paste your")
        print("Gemini key (aistudio.google.com/apikey) after GEMINI_API_KEY=")
        return

    customers = load_customers()
    customer = pick_customer(customers)
    system_prompt = build_system_prompt(customer, format_record(customer))

    print("\n--- ringing... call connected ---\n")

    # The opening line is scripted in code, not generated by the LLM:
    # compliance-critical wording should be deterministic, every call.
    opening = OPENING.format(name=customer["name"])
    print(f"Maya: {opening}\n")
    history = [{"role": "model", "text": opening}]

    while True:
        user_text = input("You: ").strip()
        if not user_text:
            continue
        if user_text.lower() in {"quit", "exit", "bye"}:
            print("\n--- call ended ---")
            break

        history.append({"role": "user", "text": user_text})
        reply = ask_brain(api_key, system_prompt, history)
        history.append({"role": "model", "text": reply})
        print(f"\nMaya: {reply}\n")


if __name__ == "__main__":
    main()
